baseURL = "/"
theme = "diary"
title = "DAITA"

# Language and i18n
defaultContentLanguage = "en"
languageCode = "en-us"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  subtitle = "My Personal Blog"
  enableOpenGraph = true
  enableTwitterCards = true
  enableReadingTime = true
  enableGitalk = false
  enableGiscus = false

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "DAITA"

[permalinks]
  posts = "/:year/:month/:title/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[security]
  enableInlineShortcodes = true

[build]
  noJSConfigInAssets = true
  writeStats = false

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "Services"
    pageRef = "/services"
    weight = 3
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 1
  [[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 2
  [[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 3
  [[menu.main]]
    url = "/posts"
    name = "Archive"
    weight = 11