baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DAITA'
theme = 'diary'




[menus]
  [[menus.main]]
    name = 'Blog'
    url = '/blog'
    weight = 2
  [[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 3
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 1