[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.147.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 정적 assets에 대한 캐싱 추가
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"